name: Autoevaluación de Ejercicios
on: [workflow_call]

jobs:
  test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Última LTS
      - name: Ejecutar ejercicios JavaScript
        run: |
          cd ejercicios-js/
          for file in *.js; do
            echo "🔍 Probando $file..."
            node "$file" || exit 1
          done

  test-py:
    needs: test-js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Verificar y crear requirements.txt
        run: |
          cd ejercicios-py/
          if [ ! -f requirements.txt ]; then
            echo "tabulate==0.9.0" > requirements.txt
          fi
      - name: Instalar dependencias Python
        run: |
          cd ejercicios-py/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar ejercicios Python
        run: |
          cd ejercicios-py/
          for file in *.py; do
            echo "🔍 Probando $file..."
            echo "----------------------------------------"
            python "$file" || exit 1
            echo "----------------------------------------"
          done