name: Verificaciones en GitHub Actions

on:
  push:

jobs:
  Verificar:
    name: Nombres de Archivos
    uses: ./.github/workflows/filenames.yml


  Ejecutar:
    name: Probar los archivos
    needs: VerificarNombres
    uses: ./.github/workflows/autorun.yml
